In [6]:
import pandas as pd
from google.colab import files

In [5]:
uploaded = files.upload()

Saving laptops.csv to laptops.csv

In [7]:
laptops=pd.read_csv("laptops.csv",encoding='latin-1')

In [8]:
laptops.head()

,Manufacturer,Model Name,Category,Screen Size,Screen,CPU,RAM,Storage,GPU,Operating System,Operating System Version,Weight,Price (Euros)
0,Apple,MacBook Pro,Ultrabook,"13.3""",IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37kg,"1339,69"
1,Apple,Macbook Air,Ultrabook,"13.3""",1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,NaN,1.34kg,"898,94"
2,HP,250 G6,Notebook,"15.6""",Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,NaN,1.86kg,"575,00"
3,Apple,MacBook Pro,Ultrabook,"15.4""",IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,NaN,1.83kg,"2537,45"
4,Apple,MacBook Pro,Ultrabook,"13.3""",IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,NaN,1.37kg,"1803,60"

In [9]:
laptops.columns=laptops.columns.str.strip().str.replace(' ','_')

In [10]:
laptops.columns

Index(['Manufacturer', 'Model_Name', 'Category', 'Screen_Size', 'Screen',
       'CPU', 'RAM', 'Storage', 'GPU', 'Operating_System',
       'Operating_System_Version', 'Weight', 'Price_(Euros)'],
      dtype='object')

In [11]:
laptops["Screen_Size"]=laptops["Screen_Size"].str.replace('"','').str.replace(",",".").str.replace('inches','').str.replace('inch','')

In [12]:
laptops["Screen_Size"].astype(float)

0       13.3
1       13.3
2       15.6
3       15.4
4       13.3
        ...
1298    14.0
1299    13.3
1300    14.0
1301    15.6
1302    15.6
Name: Screen_Size, Length: 1303, dtype: float64

In [13]:
laptops.head()

,Manufacturer,Model_Name,Category,Screen_Size,Screen,CPU,RAM,Storage,GPU,Operating_System,Operating_System_Version,Weight,Price_(Euros)
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37kg,"1339,69"
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,NaN,1.34kg,"898,94"
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,NaN,1.86kg,"575,00"
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,NaN,1.83kg,"2537,45"
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,NaN,1.37kg,"1803,60"

In [14]:
laptops["RAM"]=laptops["RAM"].str.replace('GB','').astype(int)

In [15]:
laptops.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Manufacturer              1303 non-null   object
 1   Model_Name                1303 non-null   object
 2   Category                  1303 non-null   object
 3   Screen_Size               1303 non-null   object
 4   Screen                    1303 non-null   object
 5   CPU                       1303 non-null   object
 6   RAM                       1303 non-null   int64
 7   Storage                   1303 non-null   object
 8   GPU                       1303 non-null   object
 9   Operating_System          1303 non-null   object
 10  Operating_System_Version  1133 non-null   object
 11  Weight                    1303 non-null   object
 12  Price_(Euros)             1303 non-null   object
dtypes: int64(1), object(12)
memory usage: 132.5+ KB

In [16]:
laptops["Weight"]=laptops["Weight"].str.replace('kg','').str.replace('s','').astype(float)

In [17]:
laptops["Price_(Euros)"]=laptops["Price_(Euros)"].str.replace(',','.').astype(float)

In [18]:
laptops.rename({"Price_(Euros)":"Price in Euros","Weight":"Weight In Kg","RAM":"RAM(GB)","Screen_Size":"Screen_Size in Inches"},axis=1,inplace=True)

In [19]:
laptops.head()

,Manufacturer,Model_Name,Category,Screen_Size in Inches,Screen,CPU,RAM(GB),Storage,GPU,Operating_System,Operating_System_Version,Weight In Kg,Price in Euros
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37,1339.69
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,NaN,1.34,898.94
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,NaN,1.86,575.00
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,NaN,1.83,2537.45
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,NaN,1.37,1803.60

In [20]:
laptops['Screen_Size in Inches']=laptops['Screen_Size in Inches'].astype(float)

In [21]:
laptops['Screen_Size in Inches'].describe()

count    1303.000000
mean       15.017191
std         1.426304
min        10.100000
25%        14.000000
50%        15.600000
75%        15.600000
max        18.400000
Name: Screen_Size in Inches, dtype: float64

In [22]:
laptops["gpu_manu"]=laptops['GPU'].str.split(n=1,expand=True)[0]

In [23]:
laptops['gpu_make']=laptops['GPU'].str.split(n=1,expand=True)[1]

In [24]:
laptops.head()

,Manufacturer,Model_Name,Category,Screen_Size in Inches,Screen,CPU,RAM(GB),Storage,GPU,Operating_System,Operating_System_Version,Weight In Kg,Price in Euros,gpu_manu,gpu_make
0,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8,128GB SSD,Intel Iris Plus Graphics 640,macOS,NaN,1.37,1339.69,Intel,Iris Plus Graphics 640
1,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8,128GB Flash Storage,Intel HD Graphics 6000,macOS,NaN,1.34,898.94,Intel,HD Graphics 6000
2,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8,256GB SSD,Intel HD Graphics 620,No OS,NaN,1.86,575.00,Intel,HD Graphics 620
3,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16,512GB SSD,AMD Radeon Pro 455,macOS,NaN,1.83,2537.45,AMD,Radeon Pro 455
4,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8,256GB SSD,Intel Iris Plus Graphics 650,macOS,NaN,1.37,1803.60,Intel,Iris Plus Graphics 650

In [25]:
laptops['gpu_manu'].unique()

array(['Intel', 'AMD', 'Nvidia', 'ARM'], dtype=object)

In [26]:
laptops['gpu_manu'].value_counts()

gpu_manu
Intel     722
Nvidia    400
AMD       180
ARM         1
Name: count, dtype: int64

In [29]:
laptops.to_csv('laptops_cleaned.csv',index=True)